url: https://google.com
baseurl: /

# Site settings
title: Paula Villa - Portfolio
email: pvilla1127@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Paula Villa
  pic: 1
  position: Copywriter
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/pvilla_/
  - title: facebook
    url:
  - title: linkedin
    url: https://www.linkedin.com/in/paula-villa/

# Postal address (add as many lines as necessary)
address:
  - line: Valencia
  - line: Spain

# Build settings
markdown: kramdown
permalink: pretty